### ISSUE TITLE
USER_INT content in ESI tags stays empty

### ISSUE THREAD

**Issue by internerz** [mittwald/typo3-varnishcache#9]
Hi there, 

the following ESI tag is generated:

```
<!--esi <esi:include src="http://dev.local/index.php?id=101&type=12345&identifier=07b84148523076f59cac37d2b7cea339&key=%3Cdiv%20id%3D%22c1646%22%20class%3D%22csc-default%20no-layout%20csc-space-after-25%22%3EINT_SCRIPT.d69af2d1bcd932a7b5fffe92f8433e8d%3C%2Fdiv%3E&varnish=1" />-->
```

If you add `&element=1646` (the part you can see in the first few bits of the key param) you get the correct content element, but the content isn't translated. 

Is this a bug or is there something wrong with the site? solr (the page for the search results) for example also doesn't work.

Using 1.0.2 from TER and TYPO3 6.2.26.

**Comment by internerz** [comment]
This is my varnish configuration: [typo3.vcl.txt](https://github.com/mittwald/typo3-varnishcache/files/385708/typo3.vcl.txt)

**Comment by merzilla** [comment]
Hi,
I just want to say I have the same key, like
`key=%0A<div id%3D"c90">%0A%09%0A%0A%0A%0A%09%0A%09INT_SCRIPT.d53df2a300e62171a7b4882c4b88a153%0A%0A%09%0A%0A%0A<%2Fdiv>%0A`

So by doing something like:
`$key = str_replace('%0A', '', strstr(urlencode($key), 'INT_SCRIPT.'));
                $key = strstr($key, '%09', true);`

This gives me key `INT_SCRIPT.d53df2a300e62171a7b4882c4b88a153` in this case.

But I don´t know what is responsible for having those div and %0A and %09 there?

**Comment by ifx-cw** [comment]
There appears to be a bug in the EsiTagService when classifying an Object as "INT-Object":
the regular expression in EsiTagService::isIntObject just searches for "INT_SCRIPT" anywhere within the given content. This appears to be problematic in combination with (supposedly) nested content / stdWrap.

We solved our issues here by adjusting the regular expression - use this as function body:
return (boolean)preg_match('/^INT_SCRIPT/', $content);

For us, everything works fine since then.
